-- https://school.programmers.co.kr/learn/courses/30/lessons/59412

SELECT HOUR(DATETIME) AS HOUR, COUNT(HOUR(DATETIME))
FROM ANIMAL_OUTS
GROUP BY HOUR
HAVING HOUR >= 9 AND
       HOUR <= 19
ORDER BY HOUR;